package com.pwrd.war.gameserver.qiecuo.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class QiecuoMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_QieCuo_Request_Message, CGQiecuoRequestMessage.class);
		map.put(MessageType.CG_QieCuo_Answer_Message, CGQiecuoAnswerMessage.class);
		return map;
	}

}
