package com.pwrd.war.gameserver.item.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class ItemMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_REQ_BAGINFO, CGReqBaginfo.class);
		map.put(MessageType.CG_MOVE_ITEM, CGMoveItem.class);
		map.put(MessageType.CG_TIDY_BAG, CGTidyBag.class);
		map.put(MessageType.CG_DROP_ITEM, CGDropItem.class);
		map.put(MessageType.CG_USE_ITEM, CGUseItem.class);
		map.put(MessageType.CG_SELL_ITEM, CGSellItem.class);
		map.put(MessageType.CG_SPLIT_ITEM, CGSplitItem.class);
		map.put(MessageType.CG_REQ_ITEM_INFO, CGReqItemInfo.class);
		map.put(MessageType.CG_ENHANCE_EQUIP, CGEnhanceEquip.class);
		map.put(MessageType.CG_ENHANCE_EQUIP_INFO, CGEnhanceEquipInfo.class);
		map.put(MessageType.CG_SPAND_BAG_GOLD, CGSpandBagGold.class);
		map.put(MessageType.CG_SPAND_BAG, CGSpandBag.class);
		map.put(MessageType.CG_XINGHUN_ACTIVATE, CGXinghunActivate.class);
		map.put(MessageType.CG_XINGHUN_DESTRUCT, CGXinghunDestruct.class);
		map.put(MessageType.CG_XINGHUN_XILIAN, CGXinghunXilian.class);
		map.put(MessageType.CG_XINGHUN_ADD, CGXinghunAdd.class);
		map.put(MessageType.CG_XINGHUN_RED, CGXinghunRed.class);
		map.put(MessageType.CG_XINGHUN_PILIANG_XILIAN, CGXinghunPiliangXilian.class);
		map.put(MessageType.CG_XINGHUN_PILIANG_XILIAN_REMAIN, CGXinghunPiliangXilianRemain.class);
		map.put(MessageType.CG_GET_REEL_INFO, CGGetReelInfo.class);
		return map;
	}

}
