package com.pwrd.war.gameserver.scene.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class SceneMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_SCENE_LINE, CGSceneLine.class);
		map.put(MessageType.CG_SWITCH_SCENE_LINE, CGSwitchSceneLine.class);
		map.put(MessageType.CG_SWITCH_SCENE, CGSwitchScene.class);
		map.put(MessageType.CG_PLAYER_POS, CGPlayerPos.class);
		map.put(MessageType.CG_PLAYER_MOVE, CGPlayerMove.class);
		map.put(MessageType.CG_PLAYER_JUMP, CGPlayerJump.class);
		map.put(MessageType.CG_PLAYER_SIT, CGPlayerSit.class);
		map.put(MessageType.CG_PLAYER_STAND, CGPlayerStand.class);
		return map;
	}

}
