package com.pwrd.war.gameserver.buff.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class BuffMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_Not_Hp_Bag_Message, CGNotHpBagMessage.class);
		map.put(MessageType.CG_Hp_Bag_Message, CGHpBagMessage.class);
		map.put(MessageType.CG_Romove_Buffer, CGRomoveBuffer.class);
		return map;
	}

}
