package com.pwrd.war.gameserver.player.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class PlayerMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_PLAYER_COOKIE_LOGIN, CGPlayerCookieLogin.class);
		map.put(MessageType.CG_CREATE_ROLE, CGCreateRole.class);
		map.put(MessageType.CG_PLAYER_ENTER, CGPlayerEnter.class);
		map.put(MessageType.CG_ENTER_SCENE, CGEnterScene.class);
		map.put(MessageType.CG_PLAYER_GUIDE, CGPlayerGuide.class);
		map.put(MessageType.CG_PLAYER_GUIDE_LIST, CGPlayerGuideList.class);
		return map;
	}

}
