package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.arena.msg.CGArenaList;
import com.pwrd.war.gameserver.arena.msg.GCArenaList;
import com.pwrd.war.gameserver.arena.msg.CGArenaFight;
import com.pwrd.war.gameserver.arena.msg.CGArenaRankingList;
import com.pwrd.war.gameserver.arena.msg.GCArenaRankingList;
import com.pwrd.war.gameserver.arena.msg.CGArenaAchievementList;
import com.pwrd.war.gameserver.arena.msg.GCArenaAchievementList;
import com.pwrd.war.gameserver.arena.msg.CGArenaAddTime;
import com.pwrd.war.gameserver.arena.msg.CGArenaUpdateMsg;
import com.pwrd.war.gameserver.arena.msg.GCArenaAddTime;
import com.pwrd.war.gameserver.arena.msg.GCArenaNotice;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class ArenaMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_ARENA_LIST, CGArenaList.class);
		map.put(MessageType.GC_ARENA_LIST, GCArenaList.class);
		map.put(MessageType.CG_ARENA_FIGHT, CGArenaFight.class);
		map.put(MessageType.CG_ARENA_RANKING_LIST, CGArenaRankingList.class);
		map.put(MessageType.GC_ARENA_RANKING_LIST, GCArenaRankingList.class);
		map.put(MessageType.CG_ARENA_ACHIEVEMENT_LIST, CGArenaAchievementList.class);
		map.put(MessageType.GC_ARENA_ACHIEVEMENT_LIST, GCArenaAchievementList.class);
		map.put(MessageType.CG_ARENA_ADD_TIME, CGArenaAddTime.class);
		map.put(MessageType.CG_ARENA_UPDATE_MSG, CGArenaUpdateMsg.class);
		map.put(MessageType.GC_ARENA_ADD_TIME, GCArenaAddTime.class);
		map.put(MessageType.GC_ARENA_NOTICE, GCArenaNotice.class);
		return map;
	}

}
