package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.buff.msg.GCBufferInitMessage;
import com.pwrd.war.gameserver.buff.msg.GCBuffChangeMessage;
import com.pwrd.war.gameserver.buff.msg.CGNotHpBagMessage;
import com.pwrd.war.gameserver.buff.msg.GCNotHpBagMessage;
import com.pwrd.war.gameserver.buff.msg.CGHpBagMessage;
import com.pwrd.war.gameserver.buff.msg.CGRomoveBuffer;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class BuffMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.GC_Buffer_Init_Message, GCBufferInitMessage.class);
		map.put(MessageType.GC_Buff_Change_Message, GCBuffChangeMessage.class);
		map.put(MessageType.CG_Not_Hp_Bag_Message, CGNotHpBagMessage.class);
		map.put(MessageType.GC_Not_Hp_Bag_Message, GCNotHpBagMessage.class);
		map.put(MessageType.CG_Hp_Bag_Message, CGHpBagMessage.class);
		map.put(MessageType.CG_Romove_Buffer, CGRomoveBuffer.class);
		return map;
	}

}
