package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.form.msg.GCForm;
import com.pwrd.war.gameserver.form.msg.CGForm;
import com.pwrd.war.gameserver.form.msg.CGFormPosition;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class FormMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.GC_Form, GCForm.class);
		map.put(MessageType.CG_Form, CGForm.class);
		map.put(MessageType.CG_Form_Position, CGFormPosition.class);
		return map;
	}

}
