package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.friend.msg.CGFriendAdd;
import com.pwrd.war.gameserver.friend.msg.CGFriendGetList;
import com.pwrd.war.gameserver.friend.msg.CGFriendDel;
import com.pwrd.war.gameserver.friend.msg.CGFriendAddBlack;
import com.pwrd.war.gameserver.friend.msg.CGFriendDelBlack;
import com.pwrd.war.gameserver.friend.msg.GCFriendList;
import com.pwrd.war.gameserver.friend.msg.GCFriendNewMessage;
import com.pwrd.war.gameserver.friend.msg.GCFriendAddOrUpdate;
import com.pwrd.war.gameserver.friend.msg.GCFriendDel;
import com.pwrd.war.gameserver.friend.msg.GCFriendLatestLink;
import com.pwrd.war.gameserver.friend.msg.GCFriendLatestAddOrUpdate;
import com.pwrd.war.gameserver.friend.msg.GCFriendLatestDel;
import com.pwrd.war.gameserver.friend.msg.GCFriendBlackAdd;
import com.pwrd.war.gameserver.friend.msg.GCFriendBlackDel;
import com.pwrd.war.gameserver.friend.msg.GCFriendBlacks;
import com.pwrd.war.gameserver.friend.msg.CGFriendGetInfo;
import com.pwrd.war.gameserver.friend.msg.GCFriendGetInfo;
import com.pwrd.war.gameserver.friend.msg.GCFriendAddRes;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class FriendMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_FRIEND_ADD, CGFriendAdd.class);
		map.put(MessageType.CG_FRIEND_GET_LIST, CGFriendGetList.class);
		map.put(MessageType.CG_FRIEND_DEL, CGFriendDel.class);
		map.put(MessageType.CG_FRIEND_ADD_BLACK, CGFriendAddBlack.class);
		map.put(MessageType.CG_FRIEND_DEL_BLACK, CGFriendDelBlack.class);
		map.put(MessageType.GC_FRIEND_LIST, GCFriendList.class);
		map.put(MessageType.GC_FRIEND_NEW_MESSAGE, GCFriendNewMessage.class);
		map.put(MessageType.GC_FRIEND_ADD_OR_UPDATE, GCFriendAddOrUpdate.class);
		map.put(MessageType.GC_FRIEND_DEL, GCFriendDel.class);
		map.put(MessageType.GC_FRIEND_LATEST_LINK, GCFriendLatestLink.class);
		map.put(MessageType.GC_FRIEND_LATEST_ADD_OR_UPDATE, GCFriendLatestAddOrUpdate.class);
		map.put(MessageType.GC_FRIEND_LATEST_DEL, GCFriendLatestDel.class);
		map.put(MessageType.GC_FRIEND_BLACK_ADD, GCFriendBlackAdd.class);
		map.put(MessageType.GC_FRIEND_BLACK_DEL, GCFriendBlackDel.class);
		map.put(MessageType.GC_FRIEND_BLACKS, GCFriendBlacks.class);
		map.put(MessageType.CG_FRIEND_GET_INFO, CGFriendGetInfo.class);
		map.put(MessageType.GC_FRIEND_GET_INFO, GCFriendGetInfo.class);
		map.put(MessageType.GC_FRIEND_ADD_RES, GCFriendAddRes.class);
		return map;
	}

}
