package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.human.msg.GCHumanDetailInfo;
import com.pwrd.war.gameserver.human.msg.CGEnterHome;
import com.pwrd.war.gameserver.human.msg.CGQueryHumanInfo;
import com.pwrd.war.gameserver.human.msg.CGQueryOtherRoleInfo;
import com.pwrd.war.gameserver.human.msg.GCSceneUpdateRole;
import com.pwrd.war.gameserver.human.msg.GCSceneRoleList;
import com.pwrd.war.gameserver.human.msg.GCSceneAddRole;
import com.pwrd.war.gameserver.human.msg.GCSceneDelRole;
import com.pwrd.war.gameserver.human.msg.GCPropertyChangedNumber;
import com.pwrd.war.gameserver.human.msg.GCPropertyChangedString;
import com.pwrd.war.gameserver.human.msg.GCQueueInfo;
import com.pwrd.war.gameserver.human.msg.CGOpenEquipenhanceCdqueue;
import com.pwrd.war.gameserver.human.msg.CGReleaseCdqueue;
import com.pwrd.war.gameserver.human.msg.CGArchiveList;
import com.pwrd.war.gameserver.human.msg.GCArchiveList;
import com.pwrd.war.gameserver.human.msg.CGJoinChannel;
import com.pwrd.war.gameserver.human.msg.CGUnjoinChannel;
import com.pwrd.war.gameserver.human.msg.CGLevelupGrow;
import com.pwrd.war.gameserver.human.msg.CGGrowProps;
import com.pwrd.war.gameserver.human.msg.GCGrowProps;
import com.pwrd.war.gameserver.human.msg.CGStartXiulian;
import com.pwrd.war.gameserver.human.msg.GCStartXiulian;
import com.pwrd.war.gameserver.human.msg.CGEndXiulian;
import com.pwrd.war.gameserver.human.msg.GCEndXiulian;
import com.pwrd.war.gameserver.human.msg.CGXiulianUpLevel;
import com.pwrd.war.gameserver.human.msg.CGXiulianCollectSymbol;
import com.pwrd.war.gameserver.human.msg.GCXiulianCollectSymbol;
import com.pwrd.war.gameserver.human.msg.GCXiulianBeCollectSymbol;
import com.pwrd.war.gameserver.human.msg.CGModifyPersonsign;
import com.pwrd.war.gameserver.human.msg.GCGoldGrowCri;
import com.pwrd.war.gameserver.human.msg.GCJingjieProps;
import com.pwrd.war.gameserver.human.msg.CGJingjieProps;
import com.pwrd.war.gameserver.human.msg.GCOnlinePrize;
import com.pwrd.war.gameserver.human.msg.CGOnlinePrize;
import com.pwrd.war.gameserver.human.msg.GCOnlinePrizeRes;
import com.pwrd.war.gameserver.human.msg.GCLoginPrizeShow;
import com.pwrd.war.gameserver.human.msg.CGGetLoginPrize;
import com.pwrd.war.gameserver.human.msg.GCLoginPrize;
import com.pwrd.war.gameserver.human.msg.CGLoginPrize;
import com.pwrd.war.gameserver.human.msg.GCLoginPrizeRes;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class HumanMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.GC_HUMAN_DETAIL_INFO, GCHumanDetailInfo.class);
		map.put(MessageType.CG_ENTER_HOME, CGEnterHome.class);
		map.put(MessageType.CG_QUERY_HUMAN_INFO, CGQueryHumanInfo.class);
		map.put(MessageType.CG_QUERY_OTHER_ROLE_INFO, CGQueryOtherRoleInfo.class);
		map.put(MessageType.GC_SCENE_UPDATE_ROLE, GCSceneUpdateRole.class);
		map.put(MessageType.GC_SCENE_ROLE_LIST, GCSceneRoleList.class);
		map.put(MessageType.GC_SCENE_ADD_ROLE, GCSceneAddRole.class);
		map.put(MessageType.GC_SCENE_DEL_ROLE, GCSceneDelRole.class);
		map.put(MessageType.GC_PROPERTY_CHANGED_NUMBER, GCPropertyChangedNumber.class);
		map.put(MessageType.GC_PROPERTY_CHANGED_STRING, GCPropertyChangedString.class);
		map.put(MessageType.GC_QUEUE_INFO, GCQueueInfo.class);
		map.put(MessageType.CG_OPEN_EQUIPENHANCE_CDQUEUE, CGOpenEquipenhanceCdqueue.class);
		map.put(MessageType.CG_RELEASE_CDQUEUE, CGReleaseCdqueue.class);
		map.put(MessageType.CG_ARCHIVE_LIST, CGArchiveList.class);
		map.put(MessageType.GC_ARCHIVE_LIST, GCArchiveList.class);
		map.put(MessageType.CG_JOIN_CHANNEL, CGJoinChannel.class);
		map.put(MessageType.CG_UNJOIN_CHANNEL, CGUnjoinChannel.class);
		map.put(MessageType.CG_LEVELUP_GROW, CGLevelupGrow.class);
		map.put(MessageType.CG_GROW_PROPS, CGGrowProps.class);
		map.put(MessageType.GC_GROW_PROPS, GCGrowProps.class);
		map.put(MessageType.CG_START_XIULIAN, CGStartXiulian.class);
		map.put(MessageType.GC_START_XIULIAN, GCStartXiulian.class);
		map.put(MessageType.CG_END_XIULIAN, CGEndXiulian.class);
		map.put(MessageType.GC_END_XIULIAN, GCEndXiulian.class);
		map.put(MessageType.CG_XIULIAN_UP_LEVEL, CGXiulianUpLevel.class);
		map.put(MessageType.CG_XIULIAN_COLLECT_SYMBOL, CGXiulianCollectSymbol.class);
		map.put(MessageType.GC_XIULIAN_COLLECT_SYMBOL, GCXiulianCollectSymbol.class);
		map.put(MessageType.GC_XIULIAN_BE_COLLECT_SYMBOL, GCXiulianBeCollectSymbol.class);
		map.put(MessageType.CG_MODIFY_PERSONSIGN, CGModifyPersonsign.class);
		map.put(MessageType.GC_GOLD_GROW_CRI, GCGoldGrowCri.class);
		map.put(MessageType.GC_JingJie_Props, GCJingjieProps.class);
		map.put(MessageType.CG_JingJie_Props, CGJingjieProps.class);
		map.put(MessageType.GC_ONLINE_PRIZE, GCOnlinePrize.class);
		map.put(MessageType.CG_ONLINE_PRIZE, CGOnlinePrize.class);
		map.put(MessageType.GC_ONLINE_PRIZE_RES, GCOnlinePrizeRes.class);
		map.put(MessageType.GC_LOGIN_PRIZE_SHOW, GCLoginPrizeShow.class);
		map.put(MessageType.CG_GET_LOGIN_PRIZE, CGGetLoginPrize.class);
		map.put(MessageType.GC_LOGIN_PRIZE, GCLoginPrize.class);
		map.put(MessageType.CG_LOGIN_PRIZE, CGLoginPrize.class);
		map.put(MessageType.GC_LOGIN_PRIZE_RES, GCLoginPrizeRes.class);
		return map;
	}

}
