package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.item.msg.GCBagUpdate;
import com.pwrd.war.gameserver.item.msg.GCItemUpdate;
import com.pwrd.war.gameserver.item.msg.GCRemoveItem;
import com.pwrd.war.gameserver.item.msg.GCSwapItem;
import com.pwrd.war.gameserver.item.msg.GCResetCapacity;
import com.pwrd.war.gameserver.item.msg.CGReqBaginfo;
import com.pwrd.war.gameserver.item.msg.CGMoveItem;
import com.pwrd.war.gameserver.item.msg.CGTidyBag;
import com.pwrd.war.gameserver.item.msg.CGDropItem;
import com.pwrd.war.gameserver.item.msg.CGUseItem;
import com.pwrd.war.gameserver.item.msg.CGSellItem;
import com.pwrd.war.gameserver.item.msg.GCItemStartCd;
import com.pwrd.war.gameserver.item.msg.CGSplitItem;
import com.pwrd.war.gameserver.item.msg.CGReqItemInfo;
import com.pwrd.war.gameserver.item.msg.GCResItemInfo;
import com.pwrd.war.gameserver.item.msg.CGEnhanceEquip;
import com.pwrd.war.gameserver.item.msg.GCEnhanceEquip;
import com.pwrd.war.gameserver.item.msg.CGEnhanceEquipInfo;
import com.pwrd.war.gameserver.item.msg.GCEnhanceEquipInfo;
import com.pwrd.war.gameserver.item.msg.GCUseReel;
import com.pwrd.war.gameserver.item.msg.CGSpandBagGold;
import com.pwrd.war.gameserver.item.msg.GCSpandBagGold;
import com.pwrd.war.gameserver.item.msg.CGSpandBag;
import com.pwrd.war.gameserver.item.msg.CGXinghunActivate;
import com.pwrd.war.gameserver.item.msg.GCXinghunActivate;
import com.pwrd.war.gameserver.item.msg.CGXinghunDestruct;
import com.pwrd.war.gameserver.item.msg.CGXinghunXilian;
import com.pwrd.war.gameserver.item.msg.GCXinghunXilian;
import com.pwrd.war.gameserver.item.msg.CGXinghunAdd;
import com.pwrd.war.gameserver.item.msg.CGXinghunRed;
import com.pwrd.war.gameserver.item.msg.CGXinghunPiliangXilian;
import com.pwrd.war.gameserver.item.msg.GCXinghunPiliangXilian;
import com.pwrd.war.gameserver.item.msg.CGXinghunPiliangXilianRemain;
import com.pwrd.war.gameserver.item.msg.GCXinghunPiliangXilianRemain;
import com.pwrd.war.gameserver.item.msg.CGGetReelInfo;
import com.pwrd.war.gameserver.item.msg.GCGetReelInfo;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class ItemMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.GC_BAG_UPDATE, GCBagUpdate.class);
		map.put(MessageType.GC_ITEM_UPDATE, GCItemUpdate.class);
		map.put(MessageType.GC_REMOVE_ITEM, GCRemoveItem.class);
		map.put(MessageType.GC_SWAP_ITEM, GCSwapItem.class);
		map.put(MessageType.GC_RESET_CAPACITY, GCResetCapacity.class);
		map.put(MessageType.CG_REQ_BAGINFO, CGReqBaginfo.class);
		map.put(MessageType.CG_MOVE_ITEM, CGMoveItem.class);
		map.put(MessageType.CG_TIDY_BAG, CGTidyBag.class);
		map.put(MessageType.CG_DROP_ITEM, CGDropItem.class);
		map.put(MessageType.CG_USE_ITEM, CGUseItem.class);
		map.put(MessageType.CG_SELL_ITEM, CGSellItem.class);
		map.put(MessageType.GC_ITEM_START_CD, GCItemStartCd.class);
		map.put(MessageType.CG_SPLIT_ITEM, CGSplitItem.class);
		map.put(MessageType.CG_REQ_ITEM_INFO, CGReqItemInfo.class);
		map.put(MessageType.GC_RES_ITEM_INFO, GCResItemInfo.class);
		map.put(MessageType.CG_ENHANCE_EQUIP, CGEnhanceEquip.class);
		map.put(MessageType.GC_ENHANCE_EQUIP, GCEnhanceEquip.class);
		map.put(MessageType.CG_ENHANCE_EQUIP_INFO, CGEnhanceEquipInfo.class);
		map.put(MessageType.GC_ENHANCE_EQUIP_INFO, GCEnhanceEquipInfo.class);
		map.put(MessageType.GC_USE_REEL, GCUseReel.class);
		map.put(MessageType.CG_SPAND_BAG_GOLD, CGSpandBagGold.class);
		map.put(MessageType.GC_SPAND_BAG_GOLD, GCSpandBagGold.class);
		map.put(MessageType.CG_SPAND_BAG, CGSpandBag.class);
		map.put(MessageType.CG_XINGHUN_ACTIVATE, CGXinghunActivate.class);
		map.put(MessageType.GC_XINGHUN_ACTIVATE, GCXinghunActivate.class);
		map.put(MessageType.CG_XINGHUN_DESTRUCT, CGXinghunDestruct.class);
		map.put(MessageType.CG_XINGHUN_XILIAN, CGXinghunXilian.class);
		map.put(MessageType.GC_XINGHUN_XILIAN, GCXinghunXilian.class);
		map.put(MessageType.CG_XINGHUN_ADD, CGXinghunAdd.class);
		map.put(MessageType.CG_XINGHUN_RED, CGXinghunRed.class);
		map.put(MessageType.CG_XINGHUN_PILIANG_XILIAN, CGXinghunPiliangXilian.class);
		map.put(MessageType.GC_XINGHUN_PILIANG_XILIAN, GCXinghunPiliangXilian.class);
		map.put(MessageType.CG_XINGHUN_PILIANG_XILIAN_REMAIN, CGXinghunPiliangXilianRemain.class);
		map.put(MessageType.GC_XINGHUN_PILIANG_XILIAN_REMAIN, GCXinghunPiliangXilianRemain.class);
		map.put(MessageType.CG_GET_REEL_INFO, CGGetReelInfo.class);
		map.put(MessageType.GC_GET_REEL_INFO, GCGetReelInfo.class);
		return map;
	}

}
