package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.mall.msg.CGMallList;
import com.pwrd.war.gameserver.mall.msg.GCMallList;
import com.pwrd.war.gameserver.mall.msg.CGRedeemList;
import com.pwrd.war.gameserver.mall.msg.GCRedeemList;
import com.pwrd.war.gameserver.mall.msg.CGMallBuy;
import com.pwrd.war.gameserver.mall.msg.GCMallBuy;
import com.pwrd.war.gameserver.mall.msg.CGRedeemBuy;
import com.pwrd.war.gameserver.mall.msg.GCRedeemBuy;
import com.pwrd.war.gameserver.mall.msg.CGMallSell;
import com.pwrd.war.gameserver.mall.msg.GCMallSell;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class MallMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_MALL_LIST, CGMallList.class);
		map.put(MessageType.GC_MALL_LIST, GCMallList.class);
		map.put(MessageType.CG_REDEEM_LIST, CGRedeemList.class);
		map.put(MessageType.GC_REDEEM_LIST, GCRedeemList.class);
		map.put(MessageType.CG_MALL_BUY, CGMallBuy.class);
		map.put(MessageType.GC_MALL_BUY, GCMallBuy.class);
		map.put(MessageType.CG_REDEEM_BUY, CGRedeemBuy.class);
		map.put(MessageType.GC_REDEEM_BUY, GCRedeemBuy.class);
		map.put(MessageType.CG_MALL_SELL, CGMallSell.class);
		map.put(MessageType.GC_MALL_SELL, GCMallSell.class);
		return map;
	}

}
