package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.monster.msg.GCMonsterList;
import com.pwrd.war.gameserver.monster.msg.GCAddMonster;
import com.pwrd.war.gameserver.monster.msg.GCDelMonster;
import com.pwrd.war.gameserver.monster.msg.GCMonsterMove;
import com.pwrd.war.gameserver.monster.msg.GCMonsterStopMove;
import com.pwrd.war.gameserver.monster.msg.CGStepMonster;
import com.pwrd.war.gameserver.monster.msg.GCMonsterHpDec;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class MonsterMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.GC_MONSTER_LIST, GCMonsterList.class);
		map.put(MessageType.GC_ADD_MONSTER, GCAddMonster.class);
		map.put(MessageType.GC_DEL_MONSTER, GCDelMonster.class);
		map.put(MessageType.GC_MONSTER_MOVE, GCMonsterMove.class);
		map.put(MessageType.GC_MONSTER_STOP_MOVE, GCMonsterStopMove.class);
		map.put(MessageType.CG_STEP_MONSTER, CGStepMonster.class);
		map.put(MessageType.GC_MONSTER_HP_DEC, GCMonsterHpDec.class);
		return map;
	}

}
