package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.player.msg.CGPlayerCookieLogin;
import com.pwrd.war.gameserver.player.msg.GCLoginSuccess;
import com.pwrd.war.gameserver.player.msg.GCLoginFailed;
import com.pwrd.war.gameserver.player.msg.GCRoleInfo;
import com.pwrd.war.gameserver.player.msg.CGCreateRole;
import com.pwrd.war.gameserver.player.msg.GCFailedMsg;
import com.pwrd.war.gameserver.player.msg.CGPlayerEnter;
import com.pwrd.war.gameserver.player.msg.GCSceneInfo;
import com.pwrd.war.gameserver.player.msg.CGEnterScene;
import com.pwrd.war.gameserver.player.msg.GCEnterScene;
import com.pwrd.war.gameserver.player.msg.GCNotifyException;
import com.pwrd.war.gameserver.player.msg.CGPlayerGuide;
import com.pwrd.war.gameserver.player.msg.CGPlayerGuideList;
import com.pwrd.war.gameserver.player.msg.GCPlayerGuideList;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class PlayerMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_PLAYER_COOKIE_LOGIN, CGPlayerCookieLogin.class);
		map.put(MessageType.GC_LOGIN_SUCCESS, GCLoginSuccess.class);
		map.put(MessageType.GC_LOGIN_FAILED, GCLoginFailed.class);
		map.put(MessageType.GC_ROLE_INFO, GCRoleInfo.class);
		map.put(MessageType.CG_CREATE_ROLE, CGCreateRole.class);
		map.put(MessageType.GC_FAILED_MSG, GCFailedMsg.class);
		map.put(MessageType.CG_PLAYER_ENTER, CGPlayerEnter.class);
		map.put(MessageType.GC_SCENE_INFO, GCSceneInfo.class);
		map.put(MessageType.CG_ENTER_SCENE, CGEnterScene.class);
		map.put(MessageType.GC_ENTER_SCENE, GCEnterScene.class);
		map.put(MessageType.GC_NOTIFY_EXCEPTION, GCNotifyException.class);
		map.put(MessageType.CG_PLAYER_GUIDE, CGPlayerGuide.class);
		map.put(MessageType.CG_PLAYER_GUIDE_LIST, CGPlayerGuideList.class);
		map.put(MessageType.GC_PLAYER_GUIDE_LIST, GCPlayerGuideList.class);
		return map;
	}

}
