package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.prize.msg.CGPrizePlatformList;
import com.pwrd.war.gameserver.prize.msg.GCPrizePlatformList;
import com.pwrd.war.gameserver.prize.msg.CGPrizePlatformGet;
import com.pwrd.war.gameserver.prize.msg.GCPrizePlatformGetSuccess;
import com.pwrd.war.gameserver.prize.msg.CGPrizeUserList;
import com.pwrd.war.gameserver.prize.msg.GCPrizeUserList;
import com.pwrd.war.gameserver.prize.msg.CGPrizeUserGet;
import com.pwrd.war.gameserver.prize.msg.GCPrizeUserGetSuccess;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class PrizeMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_PRIZE_PLATFORM_LIST, CGPrizePlatformList.class);
		map.put(MessageType.GC_PRIZE_PLATFORM_LIST, GCPrizePlatformList.class);
		map.put(MessageType.CG_PRIZE_PLATFORM_GET, CGPrizePlatformGet.class);
		map.put(MessageType.GC_PRIZE_PLATFORM_GET_SUCCESS, GCPrizePlatformGetSuccess.class);
		map.put(MessageType.CG_PRIZE_USER_LIST, CGPrizeUserList.class);
		map.put(MessageType.GC_PRIZE_USER_LIST, GCPrizeUserList.class);
		map.put(MessageType.CG_PRIZE_USER_GET, CGPrizeUserGet.class);
		map.put(MessageType.GC_PRIZE_USER_GET_SUCCESS, GCPrizeUserGetSuccess.class);
		return map;
	}

}
