package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.qiecuo.msg.CGQiecuoRequestMessage;
import com.pwrd.war.gameserver.qiecuo.msg.GCQiecuoRequestMessage;
import com.pwrd.war.gameserver.qiecuo.msg.CGQiecuoAnswerMessage;
import com.pwrd.war.gameserver.qiecuo.msg.GCQiecuoAnswerMessage;
import com.pwrd.war.gameserver.qiecuo.msg.GCQiecuoResultMessage;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class QiecuoMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_QieCuo_Request_Message, CGQiecuoRequestMessage.class);
		map.put(MessageType.GC_QieCuo_Request_Message, GCQiecuoRequestMessage.class);
		map.put(MessageType.CG_QieCuo_Answer_Message, CGQiecuoAnswerMessage.class);
		map.put(MessageType.GC_QieCuo_Answer_Message, GCQiecuoAnswerMessage.class);
		map.put(MessageType.GC_QieCuo_Result_Message, GCQiecuoResultMessage.class);
		return map;
	}

}
