package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.quest.msg.CGQuestList;
import com.pwrd.war.gameserver.quest.msg.GCQuestList;
import com.pwrd.war.gameserver.quest.msg.GCQuestUpdate;
import com.pwrd.war.gameserver.quest.msg.GCFinishQuest;
import com.pwrd.war.gameserver.quest.msg.CGAcceptQuest;
import com.pwrd.war.gameserver.quest.msg.CGGiveUpQuest;
import com.pwrd.war.gameserver.quest.msg.CGFinishQuest;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class QuestMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_QUEST_LIST, CGQuestList.class);
		map.put(MessageType.GC_QUEST_LIST, GCQuestList.class);
		map.put(MessageType.GC_QUEST_UPDATE, GCQuestUpdate.class);
		map.put(MessageType.GC_FINISH_QUEST, GCFinishQuest.class);
		map.put(MessageType.CG_ACCEPT_QUEST, CGAcceptQuest.class);
		map.put(MessageType.CG_GIVE_UP_QUEST, CGGiveUpQuest.class);
		map.put(MessageType.CG_FINISH_QUEST, CGFinishQuest.class);
		return map;
	}

}
