package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.research.msg.CGResearchList;
import com.pwrd.war.gameserver.research.msg.GCResearchList;
import com.pwrd.war.gameserver.research.msg.CGResearchStart;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class ResearchMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_RESEARCH_LIST, CGResearchList.class);
		map.put(MessageType.GC_RESEARCH_LIST, GCResearchList.class);
		map.put(MessageType.CG_RESEARCH_START, CGResearchStart.class);
		return map;
	}

}
