package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.scene.msg.CGSceneLine;
import com.pwrd.war.gameserver.scene.msg.GCSceneLine;
import com.pwrd.war.gameserver.scene.msg.CGSwitchSceneLine;
import com.pwrd.war.gameserver.scene.msg.GCSwitchSceneLine;
import com.pwrd.war.gameserver.scene.msg.GCTeamSwitchSceneLine;
import com.pwrd.war.gameserver.scene.msg.CGSwitchScene;
import com.pwrd.war.gameserver.scene.msg.GCSwitchScene;
import com.pwrd.war.gameserver.scene.msg.CGPlayerPos;
import com.pwrd.war.gameserver.scene.msg.GCPlayerPos;
import com.pwrd.war.gameserver.scene.msg.GCPlayerChangePos;
import com.pwrd.war.gameserver.scene.msg.CGPlayerMove;
import com.pwrd.war.gameserver.scene.msg.GCPlayerMove;
import com.pwrd.war.gameserver.scene.msg.CGPlayerJump;
import com.pwrd.war.gameserver.scene.msg.GCPlayerJump;
import com.pwrd.war.gameserver.scene.msg.CGPlayerSit;
import com.pwrd.war.gameserver.scene.msg.GCPlayerSit;
import com.pwrd.war.gameserver.scene.msg.CGPlayerStand;
import com.pwrd.war.gameserver.scene.msg.GCPlayerStand;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class SceneMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_SCENE_LINE, CGSceneLine.class);
		map.put(MessageType.GC_SCENE_LINE, GCSceneLine.class);
		map.put(MessageType.CG_SWITCH_SCENE_LINE, CGSwitchSceneLine.class);
		map.put(MessageType.GC_SWITCH_SCENE_LINE, GCSwitchSceneLine.class);
		map.put(MessageType.GC_TEAM_SWITCH_SCENE_LINE, GCTeamSwitchSceneLine.class);
		map.put(MessageType.CG_SWITCH_SCENE, CGSwitchScene.class);
		map.put(MessageType.GC_SWITCH_SCENE, GCSwitchScene.class);
		map.put(MessageType.CG_PLAYER_POS, CGPlayerPos.class);
		map.put(MessageType.GC_PLAYER_POS, GCPlayerPos.class);
		map.put(MessageType.GC_PLAYER_CHANGE_POS, GCPlayerChangePos.class);
		map.put(MessageType.CG_PLAYER_MOVE, CGPlayerMove.class);
		map.put(MessageType.GC_PLAYER_MOVE, GCPlayerMove.class);
		map.put(MessageType.CG_PLAYER_JUMP, CGPlayerJump.class);
		map.put(MessageType.GC_PLAYER_JUMP, GCPlayerJump.class);
		map.put(MessageType.CG_PLAYER_SIT, CGPlayerSit.class);
		map.put(MessageType.GC_PLAYER_SIT, GCPlayerSit.class);
		map.put(MessageType.CG_PLAYER_STAND, CGPlayerStand.class);
		map.put(MessageType.GC_PLAYER_STAND, GCPlayerStand.class);
		return map;
	}

}
