package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.secretShop.msg.CGSecretShopList;
import com.pwrd.war.gameserver.secretShop.msg.GCSecretShopList;
import com.pwrd.war.gameserver.secretShop.msg.CGSecretShopBuy;
import com.pwrd.war.gameserver.secretShop.msg.GCSecretShopBuy;
import com.pwrd.war.gameserver.secretShop.msg.GCSecretShopTimeRemain;
import com.pwrd.war.gameserver.secretShop.msg.GCSecretShopBuyInfo;
import com.pwrd.war.gameserver.secretShop.msg.CGSecretShopPreciousInfo;
import com.pwrd.war.gameserver.secretShop.msg.GCSecretShopPreciousInfo;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class SecretshopMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_SECRET_SHOP_LIST, CGSecretShopList.class);
		map.put(MessageType.GC_SECRET_SHOP_LIST, GCSecretShopList.class);
		map.put(MessageType.CG_SECRET_SHOP_BUY, CGSecretShopBuy.class);
		map.put(MessageType.GC_SECRET_SHOP_BUY, GCSecretShopBuy.class);
		map.put(MessageType.GC_SECRET_SHOP_TIME_REMAIN, GCSecretShopTimeRemain.class);
		map.put(MessageType.GC_SECRET_SHOP_BUY_INFO, GCSecretShopBuyInfo.class);
		map.put(MessageType.CG_SECRET_SHOP_PRECIOUS_INFO, CGSecretShopPreciousInfo.class);
		map.put(MessageType.GC_SECRET_SHOP_PRECIOUS_INFO, GCSecretShopPreciousInfo.class);
		return map;
	}

}
