package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.skill.msg.CGSkillUpgrade;
import com.pwrd.war.gameserver.skill.msg.GCSkillUpgrade;
import com.pwrd.war.gameserver.skill.msg.CGSkillOrder;
import com.pwrd.war.gameserver.skill.msg.GCSkillGroupName;
import com.pwrd.war.gameserver.skill.msg.GCSkillOrder;
import com.pwrd.war.gameserver.skill.msg.CGSkillCooldown;
import com.pwrd.war.gameserver.skill.msg.GCSkillCooldown;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class SkillMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_Skill_Upgrade, CGSkillUpgrade.class);
		map.put(MessageType.GC_Skill_Upgrade, GCSkillUpgrade.class);
		map.put(MessageType.CG_Skill_Order, CGSkillOrder.class);
		map.put(MessageType.GC_Skill_Group_Name, GCSkillGroupName.class);
		map.put(MessageType.GC_Skill_Order, GCSkillOrder.class);
		map.put(MessageType.CG_Skill_Cooldown, CGSkillCooldown.class);
		map.put(MessageType.GC_Skill_Cooldown, GCSkillCooldown.class);
		return map;
	}

}
