package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.story.msg.CGStoryList;
import com.pwrd.war.gameserver.story.msg.GCStoryList;
import com.pwrd.war.gameserver.story.msg.GCStoryShow;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class StoryMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_STORY_LIST, CGStoryList.class);
		map.put(MessageType.GC_STORY_LIST, GCStoryList.class);
		map.put(MessageType.GC_STORY_SHOW, GCStoryShow.class);
		return map;
	}

}
