package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.tower.msg.CGTowerInit;
import com.pwrd.war.gameserver.tower.msg.CGTowerInfo;
import com.pwrd.war.gameserver.tower.msg.GCTowerInfo;
import com.pwrd.war.gameserver.tower.msg.CGTowerRefresh;
import com.pwrd.war.gameserver.tower.msg.GCTowerRefresh;
import com.pwrd.war.gameserver.tower.msg.CGTowerSpeedup;
import com.pwrd.war.gameserver.tower.msg.GCTowerSpeedup;
import com.pwrd.war.gameserver.tower.msg.CGTowerBattle;
import com.pwrd.war.gameserver.tower.msg.GCTowerBattle;
import com.pwrd.war.gameserver.tower.msg.GCTowerBattleResult;
import com.pwrd.war.gameserver.tower.msg.GCTowerSecrete;
import com.pwrd.war.gameserver.tower.msg.GCTowerBag;
import com.pwrd.war.gameserver.tower.msg.CGTowerAutoStart;
import com.pwrd.war.gameserver.tower.msg.GCTowerAutoStart;
import com.pwrd.war.gameserver.tower.msg.GCTowerAutoCompleteOne;
import com.pwrd.war.gameserver.tower.msg.GCTowerAutoComplete;
import com.pwrd.war.gameserver.tower.msg.CGTowerAutoCancel;
import com.pwrd.war.gameserver.tower.msg.GCTowerAutoCancel;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class TowerMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_TOWER_INIT, CGTowerInit.class);
		map.put(MessageType.CG_TOWER_INFO, CGTowerInfo.class);
		map.put(MessageType.GC_TOWER_INFO, GCTowerInfo.class);
		map.put(MessageType.CG_TOWER_REFRESH, CGTowerRefresh.class);
		map.put(MessageType.GC_TOWER_REFRESH, GCTowerRefresh.class);
		map.put(MessageType.CG_TOWER_SPEEDUP, CGTowerSpeedup.class);
		map.put(MessageType.GC_TOWER_SPEEDUP, GCTowerSpeedup.class);
		map.put(MessageType.CG_TOWER_BATTLE, CGTowerBattle.class);
		map.put(MessageType.GC_TOWER_BATTLE, GCTowerBattle.class);
		map.put(MessageType.GC_TOWER_BATTLE_RESULT, GCTowerBattleResult.class);
		map.put(MessageType.GC_TOWER_SECRETE, GCTowerSecrete.class);
		map.put(MessageType.GC_TOWER_BAG, GCTowerBag.class);
		map.put(MessageType.CG_TOWER_AUTO_START, CGTowerAutoStart.class);
		map.put(MessageType.GC_TOWER_AUTO_START, GCTowerAutoStart.class);
		map.put(MessageType.GC_TOWER_AUTO_COMPLETE_ONE, GCTowerAutoCompleteOne.class);
		map.put(MessageType.GC_TOWER_AUTO_COMPLETE, GCTowerAutoComplete.class);
		map.put(MessageType.CG_TOWER_AUTO_CANCEL, CGTowerAutoCancel.class);
		map.put(MessageType.GC_TOWER_AUTO_CANCEL, GCTowerAutoCancel.class);
		return map;
	}

}
