package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.transferVocation.msg.CGTransferVocationMessage;
import com.pwrd.war.gameserver.transferVocation.msg.GCTransferVocationResult;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class TransfervocationMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_Transfer_Vocation_Message, CGTransferVocationMessage.class);
		map.put(MessageType.GC_Transfer_Vocation_Result, GCTransferVocationResult.class);
		return map;
	}

}
