package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.tree.msg.CGTreeInfo;
import com.pwrd.war.gameserver.tree.msg.GCTreeInfo;
import com.pwrd.war.gameserver.tree.msg.CGTreeShake;
import com.pwrd.war.gameserver.tree.msg.CGTreeShakeBatch;
import com.pwrd.war.gameserver.tree.msg.GCTreeShake;
import com.pwrd.war.gameserver.tree.msg.CGWaterInfo;
import com.pwrd.war.gameserver.tree.msg.GCWaterInfo;
import com.pwrd.war.gameserver.tree.msg.CGWaterMyself;
import com.pwrd.war.gameserver.tree.msg.CGWaterFriend;
import com.pwrd.war.gameserver.tree.msg.GCWaterResult;
import com.pwrd.war.gameserver.tree.msg.CGGetFruit;
import com.pwrd.war.gameserver.tree.msg.GCGetFruit;
import com.pwrd.war.gameserver.tree.msg.CGGetWaterRecord;
import com.pwrd.war.gameserver.tree.msg.GCGetWaterRecord;
import com.pwrd.war.gameserver.tree.msg.CGWaterFriendBatch;
import com.pwrd.war.gameserver.tree.msg.CGFriendWaterInfo;
import com.pwrd.war.gameserver.tree.msg.GCFriendWaterInfo;
import com.pwrd.war.gameserver.tree.msg.CGGetFriendWaterRecord;
import com.pwrd.war.gameserver.tree.msg.GCGetFriendWaterRecord;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class TreeMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_TREE_INFO, CGTreeInfo.class);
		map.put(MessageType.GC_TREE_INFO, GCTreeInfo.class);
		map.put(MessageType.CG_TREE_SHAKE, CGTreeShake.class);
		map.put(MessageType.CG_TREE_SHAKE_BATCH, CGTreeShakeBatch.class);
		map.put(MessageType.GC_TREE_SHAKE, GCTreeShake.class);
		map.put(MessageType.CG_WATER_INFO, CGWaterInfo.class);
		map.put(MessageType.GC_WATER_INFO, GCWaterInfo.class);
		map.put(MessageType.CG_WATER_MYSELF, CGWaterMyself.class);
		map.put(MessageType.CG_WATER_FRIEND, CGWaterFriend.class);
		map.put(MessageType.GC_WATER_RESULT, GCWaterResult.class);
		map.put(MessageType.CG_GET_FRUIT, CGGetFruit.class);
		map.put(MessageType.GC_GET_FRUIT, GCGetFruit.class);
		map.put(MessageType.CG_GET_WATER_RECORD, CGGetWaterRecord.class);
		map.put(MessageType.GC_GET_WATER_RECORD, GCGetWaterRecord.class);
		map.put(MessageType.CG_WATER_FRIEND_BATCH, CGWaterFriendBatch.class);
		map.put(MessageType.CG_FRIEND_WATER_INFO, CGFriendWaterInfo.class);
		map.put(MessageType.GC_FRIEND_WATER_INFO, GCFriendWaterInfo.class);
		map.put(MessageType.CG_GET_FRIEND_WATER_RECORD, CGGetFriendWaterRecord.class);
		map.put(MessageType.GC_GET_FRIEND_WATER_RECORD, GCGetFriendWaterRecord.class);
		return map;
	}

}
