package com.pwrd.war.robot.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

import com.pwrd.war.gameserver.vitality.msg.CGBuyVit;
import com.pwrd.war.gameserver.vitality.msg.GCBuyVit;
import com.pwrd.war.gameserver.vitality.msg.GCVitZero;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class VitalityMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_BUY_VIT, CGBuyVit.class);
		map.put(MessageType.GC_BUY_VIT, GCBuyVit.class);
		map.put(MessageType.GC_VIT_ZERO, GCVitZero.class);
		return map;
	}

}
