package com.pwrd.war.gameserver.skill.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class SkillMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_Skill_Upgrade, CGSkillUpgrade.class);
		map.put(MessageType.CG_Skill_Order, CGSkillOrder.class);
		map.put(MessageType.CG_Skill_Cooldown, CGSkillCooldown.class);
		return map;
	}

}
