package com.pwrd.war.gameserver.interactive.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class InteractiveMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_Look_Up_Message, CGLookUpMessage.class);
		map.put(MessageType.CG_Role_List_Message, CGRoleListMessage.class);
		map.put(MessageType.CG_Equipment_Infomation_Message, CGEquipmentInfomationMessage.class);
		map.put(MessageType.CG_Infomation_Message, CGInfomationMessage.class);
		map.put(MessageType.CG_Transfer_Vocation_Information_Message, CGTransferVocationInformationMessage.class);
		return map;
	}

}
