package com.pwrd.war.gameserver.mail.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class MailMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_MAIL_LIST, CGMailList.class);
		map.put(MessageType.CG_READ_MAIL, CGReadMail.class);
		map.put(MessageType.CG_SEND_MAIL, CGSendMail.class);
		map.put(MessageType.CG_DEL_MAIL, CGDelMail.class);
		map.put(MessageType.CG_DEL_ALL_MAIL, CGDelAllMail.class);
		map.put(MessageType.CG_SAVE_MAIL, CGSaveMail.class);
		map.put(MessageType.CG_SEND_GUILD_MAIL, CGSendGuildMail.class);
		return map;
	}

}
