package com.pwrd.war.gameserver.human.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class HumanMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_ENTER_HOME, CGEnterHome.class);
		map.put(MessageType.CG_QUERY_HUMAN_INFO, CGQueryHumanInfo.class);
		map.put(MessageType.CG_QUERY_OTHER_ROLE_INFO, CGQueryOtherRoleInfo.class);
		map.put(MessageType.CG_OPEN_EQUIPENHANCE_CDQUEUE, CGOpenEquipenhanceCdqueue.class);
		map.put(MessageType.CG_RELEASE_CDQUEUE, CGReleaseCdqueue.class);
		map.put(MessageType.CG_ARCHIVE_LIST, CGArchiveList.class);
		map.put(MessageType.CG_JOIN_CHANNEL, CGJoinChannel.class);
		map.put(MessageType.CG_UNJOIN_CHANNEL, CGUnjoinChannel.class);
		map.put(MessageType.CG_LEVELUP_GROW, CGLevelupGrow.class);
		map.put(MessageType.CG_GROW_PROPS, CGGrowProps.class);
		map.put(MessageType.CG_START_XIULIAN, CGStartXiulian.class);
		map.put(MessageType.CG_END_XIULIAN, CGEndXiulian.class);
		map.put(MessageType.CG_XIULIAN_UP_LEVEL, CGXiulianUpLevel.class);
		map.put(MessageType.CG_XIULIAN_COLLECT_SYMBOL, CGXiulianCollectSymbol.class);
		map.put(MessageType.CG_MODIFY_PERSONSIGN, CGModifyPersonsign.class);
		map.put(MessageType.CG_JingJie_Props, CGJingjieProps.class);
		map.put(MessageType.CG_ONLINE_PRIZE, CGOnlinePrize.class);
		map.put(MessageType.CG_GET_LOGIN_PRIZE, CGGetLoginPrize.class);
		map.put(MessageType.CG_LOGIN_PRIZE, CGLoginPrize.class);
		return map;
	}

}
