package com.pwrd.war.gameserver.prize.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class PrizeMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_PRIZE_PLATFORM_LIST, CGPrizePlatformList.class);
		map.put(MessageType.CG_PRIZE_PLATFORM_GET, CGPrizePlatformGet.class);
		map.put(MessageType.CG_PRIZE_USER_LIST, CGPrizeUserList.class);
		map.put(MessageType.CG_PRIZE_USER_GET, CGPrizeUserGet.class);
		return map;
	}

}
