package com.pwrd.war.gameserver.pet.msg;

import java.util.HashMap;
import java.util.Map;

import com.pwrd.war.core.msg.MessageType;
import com.pwrd.war.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class PetMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_PET_HIRE_LIST, CGPetHireList.class);
		map.put(MessageType.CG_PET_HIRE, CGPetHire.class);
		map.put(MessageType.CG_PET_FIRE, CGPetFire.class);
		map.put(MessageType.CG_PET_JINGJIU, CGPetJingjiu.class);
		return map;
	}

}
